// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJdTCAlLndq5YIQZ0kHx57xzkyIDil6O0',
    appId: '1:900269367501:web:b5dd92c4090670c5d34984',
    messagingSenderId: '900269367501',
    projectId: 'rewire-b8f1b',
    authDomain: 'rewire-b8f1b.firebaseapp.com',
    storageBucket: 'rewire-b8f1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNhwMI4S8dq9dE7rtUK5JVfPTvgurUls0',
    appId: '1:900269367501:android:0a344841b92f087ed34984',
    messagingSenderId: '900269367501',
    projectId: 'rewire-b8f1b',
    storageBucket: 'rewire-b8f1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN9xAtFT6qZoeE9yCiA8oqksiZGJQevpM',
    appId: '1:900269367501:ios:cb62581c6385fbc7d34984',
    messagingSenderId: '900269367501',
    projectId: 'rewire-b8f1b',
    storageBucket: 'rewire-b8f1b.firebasestorage.app',
    iosBundleId: 'com.rewire.rewire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN9xAtFT6qZoeE9yCiA8oqksiZGJQevpM',
    appId: '1:900269367501:ios:cb62581c6385fbc7d34984',
    messagingSenderId: '900269367501',
    projectId: 'rewire-b8f1b',
    storageBucket: 'rewire-b8f1b.firebasestorage.app',
    iosBundleId: 'com.rewire.rewire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJdTCAlLndq5YIQZ0kHx57xzkyIDil6O0',
    appId: '1:900269367501:web:0d3c64dc68c9c8abd34984',
    messagingSenderId: '900269367501',
    projectId: 'rewire-b8f1b',
    authDomain: 'rewire-b8f1b.firebaseapp.com',
    storageBucket: 'rewire-b8f1b.firebasestorage.app',
  );
}
